### ISSUE TITLE
Hide API key

### ISSUE THREAD

**Issue by MenlyCSE** [EonEnglish/Eon-English-App#134]
We need to hide the "LinkAccess" somewhere else
https://github.com/EonEnglish/Eon-English-App/blob/65b9aa83e0a4241836e86eba0b3e695e03a0f9e3/App/screens/ScheduleScreen.js#L45-L50

**Comment by B0ER** [comment]
Worklog:
Set the project up yesterday;
Have problem with acceleration for android emulator as I already use wsl2 (for docker) on process acceleration and they are conflicting.

**Comment by MenlyCSE** [comment]
This sounds troubling. I'm not familiar with wsl2, but let me know if you aren't able to find a workaround to run the emulation

**Comment by B0ER** [comment]
Hey, have several questions:
1. Why did you chose firestore? I have noticed so many requests for getting data on the Homework screen. We may optimize that, or use more an optimized way of getting data.
2. Why is the application building with minified bundles and in debugging mode we have tangled code?

Also I checked the task with encryption
I can use some libraries to load application variables from .env files which will be added into gitignore. By this way we hide all secrets from the project.
But the solution won't be working for encryption secrets like filename on google tables. As there the application uses http GET method, and the secret will be visible in url part. This part can be hooked in network observer applications like - canary.

**Comment by B0ER** [comment]
~~Checking, but for storing secrets in the running application, maybe we can use - https://www.npmjs.com/package/react-native-keychain~~
For loading .env variables - https://github.com/lugg/react-native-config

**Comment by B0ER** [comment]
Decided to implement .env configuration and secured storages (keychain store)

**Comment by B0ER** [comment]
PR is here:
https://github.com/EonEnglish/Eon-English-App/pull/160

**Comment by B0ER** [comment]
I decided to change [react-native-config](https://github.com/lugg/react-native-config) library using to react-native-dotenv
As the first one might needed additional setup for all platforms
