### ISSUE TITLE
Add debugger

### ISSUE THREAD

**Issue by MenlyCSE** [EonEnglish/Eon-English-App#165]
Add ability to debug the application locally.
Maybe usefull links:
https://github.com/jhen0409/react-native-debugger/discussions/774
https://github.com/gusgard/react-native-devsettings

Issue with `hermes`
https://github.com/expo/eas-cli/issues/1726

**Comment by B0ER** [comment]
https://medium.com/@abdulrahmanhashem/8-ways-to-debug-your-react-native-app-with-expo-the-comprehensive-guide-538655cf1684

**Comment by B0ER** [comment]
https://github.com/jhen0409/react-native-debugger/blob/master/docs/getting-started.md

**Comment by B0ER** [comment]
Made a simple react expo project on js. Checked there if the project has source-maps for js and actually they had there.
So probably, our Eon project has been broken by some configuration file - bable \ eos.json or metro tool

**Comment by B0ER** [comment]
found the reason why js-source-maps are not available for debugger.
the reason is in bable config, they don't provide it and also bable is used for nothing.
checked also all libraries' instalation guides and no mention about bable needing, for now.

**Comment by B0ER** [comment]
Example of debugging and js source maps:
![Image](https://github.com/user-attachments/assets/45b1d4aa-4ecc-490f-90bd-5d29542c9570)

**Comment by B0ER** [comment]
PR: https://github.com/EonEnglish/Eon-English-App/pull/183

**Comment by B0ER** [comment]
I was wrong, we need bable, for .env package. But I updated the config and now we have js source maps.
