### ISSUE TITLE
Handle .env keys from private repository

### ISSUE THREAD

**Issue by MenlyCSE** [EonEnglish/Eon-English-App#166]
Right now, the file is stored as a .env in our [private repository](https://github.com/EonEnglish/Eon-English-App-Secrets). I'm curious if we can create some sort of GitHub workflow to pull those secrets from the private to the public repository every time a team member runs the app

**Comment by B0ER** [comment]
@MenlyCSE, as you have private repository with .env secrets, we can try to use [github submodules](https://github.blog/open-source/git/working-with-submodules/) and only authorized members will be able to download it.

It can affect setup of the project.

(Just an idea)

**Comment by MenlyCSE** [comment]
That's such a cool idea! I'm excited to set this up, thanks!
