### ISSUE TITLE
Fix nesting if statements in VocabMatchPhotoScreen.js

### ISSUE THREAD

**Issue by MenlyCSE** [EonEnglish/Eon-English-App#65]
![Image](https://github.com/user-attachments/assets/c49e9b69-9080-4e23-8311-efbf48458156)
![Image](https://github.com/user-attachments/assets/4229a155-76bd-407c-af35-6c4f16e2f130)

**Comment by Aarush324** [comment]
First error: syntax is wrong; its suppose to isEmpty() instead of empty
Second error: only two equal signs needed
Third error: isExists() instead of exists()
Fourth Error: score has to be initialized

**Comment by MenlyCSE** [comment]
This task is for the `VocabMatchPhotoScreen.js`, different from `VocabMatchScreen.js`. Currently, it's incomplete until a pull request has been made for it

**Comment by RCosine** [comment]
I synced it to my own fork, and forgot to make a pull request for the actual Eon English GitHub. Now I have created the pull request, thank you
