### ISSUE TITLE
UI revamp/redesign

### ISSUE THREAD

**Issue by Scoare** [EonEnglish/Eon-English-App#73]
I believe the UI of the app should be redesigned to be more visually appealing and improve on user experience. Here are some but not all examples/suggestions of what could be improved:

- Some yellow buttons with white text make it slightly unreadable.

- We should consider colour choice with buttons and text so colourblind people can still read the text.

- The lesson select screen's buttons seem kind of cluttered and overwhelming.

- The overall visual design of the UI could be improved if we want to make it more aesthetically appealing however this is not necessary and more like something that would be nice to have depending on our target audience.

**Comment by MenlyCSE** [comment]
I like this suggestion. You can use our existing [Figma design](https://www.figma.com/design/QEKUmbK9a6TUb1IQa4Xxyq/EON-ENGLISH-APP?node-id=0-1&t=9IJjL4JsCQr1MI1X-1) as reference

**Comment by dondomiedungca** [comment]
Can I work on this?

**Comment by dondomiedungca** [comment]
Hi @MenlyCSE I created PR for this, https://github.com/EonEnglish/Eon-English-App/pull/158
